// Build cases: pure renderer outputs of the reference for hand-built states.
// Each build() runs inside the reference page and may only use its globals and window.__t.
export const CASES = [
  // lib (Task 3)
  { id: "lib/highlight-caesar", build: () => ({ state: {}, value: highlight(getSource("src-caesar")) }) },
  { id: "lib/highlight-weather", build: () => ({ state: {}, value: highlight(getSource("src-weather")) }) },
  { id: "lib/wrap-words", build: () => {
    const html = '"TALOS AGENT" encrypted with a shift of 7 is <span class="mono">AHSVZ HNLUA</span>.';
    const p = document.createElement("p"); p.innerHTML = html; const w = wrapWords(p); w.slice(0, 3).forEach((x) => x.classList.add("on"));
    return { state: { html, on: 3 }, value: p.innerHTML };
  } },
  // strip (Task 8)
  { id: "strip/forge-pending", build: () => { const run = __t.mk("forge"); return { state: { run }, html: stripHtml(run) }; } },
  { id: "strip/forge-planner-active", build: () => { const run = __t.mk("forge", { planner: "active" }); return { state: { run }, html: stripHtml(run) }; } },
  { id: "strip/forge-retry", build: () => { const run = __t.mk("forge", { planner: "done", forger: "active", tester: "forge" }, { links: { "planner-forger": true, "forger-tester": true } }); return { state: { run }, html: stripHtml(run) }; } },
  { id: "strip/forge-failed", build: () => { const run = __t.mk("forge", { planner: "done", forger: "forge", tester: "forge", human: "skip", learn: "done", executor: "fail", answer: "answer" }, { links: { "planner-forger": true, "forger-tester": true, "tester-human": true, "human-learn": true, "learn-executor": true, "executor-answer": true } }); run.nodes.executor.label = "Executor failed"; return { state: { run }, html: stripHtml(run) }; } },
  { id: "strip/vault", build: () => { const run = __t.mk("vault", { planner: "done", vault: "done" }, { links: { "planner-vault": true } }); return { state: { run }, html: stripHtml(run) }; } },
  { id: "strip/primitive-waiting", build: () => { const run = __t.mk("primitive", { planner: "done", primitive: "done", executor: "active" }); run.nodes.executor.label = "Executor, waiting for you"; return { state: { run }, html: stripHtml(run) }; } },
  { id: "strip/chat", build: () => { const run = __t.mk("chat", { planner: "done", answer: "answer" }, { links: { "planner-answer": true } }); return { state: { run }, html: stripHtml(run) }; } },
  { id: "strip/stopped", build: () => { const run = __t.mk("forge", { planner: "done", forger: "forge", tester: "stopped" }); run.nodes.tester.label = "Tester, stopped"; return { state: { run }, html: stripHtml(run) }; } },
  // banner, tabs (Task 8)
  { id: "banner/saved", build: () => { const run = __t.mk("forge", {}, { banner: { kind: "saved", name: "caesar_cipher", sub: "Next time a request needs a Caesar cipher, Talos skips forging and goes straight to Execute." } }); return { state: { run }, html: bannerHtml(run) }; } },
  { id: "banner/removed", build: () => { const run = __t.mk("vault", {}, { banner: { kind: "removed", name: "caesar_cipher", sub: "It failed 2 times in a row, so the next Caesar request will forge a fresh one. The .py file stays on disk." } }); return { state: { run }, html: bannerHtml(run) }; } },
  { id: "banner/none", build: () => { const run = __t.mk("forge"); return { state: { run }, html: bannerHtml(run) }; } },
  { id: "tabs/log-only", build: () => { const run = __t.mk("forge"); return { state: { run }, html: tabsHtml(run) }; } },
  { id: "tabs/forge", build: () => { const run = __t.mk("forge", {}, { tab: "tests", tabs: [{ id: "code", label: "Code" }, { id: "tests", label: "Tests", count: 5 }, { id: "attempts", label: "Attempts", count: 2 }, { id: "call", label: "Call" }] }); return { state: { run }, html: tabsHtml(run) }; } },
  // bench and idle (Task 8)
  { id: "bench/planning", build: () => { const run = newRun("Encrypt <b>x</b>"); initStrip(run, "forge"); run.label = "Planning"; S.cur.runs.push(run); S.current = run; S.viewing = run; S.busy = true; renderBench(run); return { state: { run: __t.clone(run), live: true, isCurrent: true }, html: bench.innerHTML }; } },
  { id: "bench/chat-done", build: () => { const run = newRun("What can you do?"); initStrip(run, "chat"); run.title = "No tools needed"; run.label = "Conversational"; run.status = "done"; run.nodes.planner.state = "done"; run.nodes.answer.state = "answer"; run.links["planner-answer"] = true; run.caption = "The Planner returned an empty plan. There's nothing to run, so Talos answers directly."; S.cur.runs.push(run); S.viewing = run; renderBench(run); return { state: { run: __t.clone(run), live: false, isCurrent: false }, html: bench.innerHTML }; } },
  { id: "idle/default", build: () => { renderIdle(); return { state: { count: S.vault.length, env: {}, askExec: true }, html: bench.innerHTML }; } },
  { id: "idle/key-set-ask-off", build: () => { S.env.OPENWEATHERMAP_API_KEY = "k"; S.askExec = false; S.vault = S.vault.slice(0, 12); renderIdle(); return { state: { count: 12, env: { OPENWEATHERMAP_API_KEY: "k" }, askExec: false }, html: bench.innerHTML }; } },
  // panels (Task 9)
  { id: "panel/code-typing", build: () => { const lines = getSource("src-caesar"); const run = __t.mk("forge", {}, { tab: "code", code: { file: "caesar_cipher.py", cap: "63 lines, attempt 1", lines, shown: 20, changed: null, note: "" } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/code-changed", build: () => { const lines = getSource("src-caesar"); const run = __t.mk("forge", {}, { tab: "code", code: { file: "caesar_cipher.py", cap: "63 lines, attempt 2", lines, shown: 63, changed: 48, flash: true, note: "Line 48 is new in attempt 2. Decrypt now shifts backwards instead of forwards." } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/tests-none", build: () => { const run = __t.mk("forge", {}, { tab: "tests" }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/tests-mixed", build: () => { const run = __t.mk("forge", {}, { tab: "tests", tests: { attempt: 1, list: [{ name: "test_encrypt_shifts_forward", state: "passed", why: "", drawn: true }, { name: "test_decrypt_reverses_encrypt", state: "failed", why: "AssertionError: 'HOZCG OUSBH' != 'TALOS AGENT'" }, { name: "test_preserves_case_and_spaces", state: "running", why: "" }, { name: "test_wraps_past_z", state: "waiting", why: "" }] } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/tests-smoke-prev", build: () => { const run = __t.mk("forge", {}, { tab: "tests", tests: { attempt: 2, list: [{ name: "test_a", state: "passed", why: "" }, { name: "test_b", state: "passed", why: "", drawn: true }] }, smoke: { call: 'caesar_cipher(text="TALOS AGENT", shift=7, mode="encrypt")', result: null }, attempts: [{ n: 1, ok: false, detail: "test_b\nAssertionError: x" }, { n: 2, ok: true, detail: "2 of 2 tests passed" }] }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/attempts-none", build: () => { const run = __t.mk("forge", {}, { tab: "attempts" }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/attempts", build: () => { const run = __t.mk("forge", {}, { tab: "attempts", attempts: [{ n: 1, ok: false, detail: "test_decrypt_reverses_encrypt\nAssertionError: 'HOZCG OUSBH' != 'TALOS AGENT'" }, { n: 2, ok: null, detail: "" }] }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/call-resolving", build: () => { const run = __t.mk("forge", {}, { tab: "call", call: { args: [["text", '"TALOS AGENT"'], ["shift", "7"], ["mode", '"encrypt"']], shownArgs: 0 } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/call-result-record", build: () => { const run = __t.mk("vault", {}, { tab: "call", call: { args: [["text", '"AHSVZ HNLUA"'], ["shift", "7"], ["mode", '"decrypt"']], shownArgs: 3, result: "'TALOS AGENT'", resultType: "str", record: { forged: "30 Sep 2026, 12:00", uses: "2, including this one", fails: "None yet" } } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/call-error-health", build: () => { const run = __t.mk("vault", {}, { tab: "call", call: { args: [["text", '"AHSVZ HNLUA"'], ["shift", '"seven"', true], ["mode", '"decrypt"']], shownArgs: 3, error: "TypeError: shift must be an int, got str", when: "30 Sep 2026, 12:00", health: { streak: 1, tool: "caesar_cipher", text: 'If <span class="mono">caesar_cipher</span> fails again before it next succeeds, Talos takes it out of the vault and forges a fresh one next time. One success resets the count. The .py file stays on disk either way.', retry: { q: 'Decrypt this Caesar cipher message with shift 7: "AHSVZ HNLUA"', label: "Ask again with shift 7" } } } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/call-no-args", build: () => { const run = __t.mk("primitive", {}, { tab: "call", call: { args: [], noArgs: true, argsCap: "Takes no arguments", resultCap: "Output" } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/call-pending-approval", build: () => { const run = __t.mk("primitive", {}, { tab: "call", call: { args: [["code", '"print(1)"']], argsCap: "Written by the Executor", shownArgs: 1, resultCap: "Output", pending: "Waiting for your approval" } }); return { state: { run }, html: panelHtml(run) }; } },
  { id: "panel/history", build: () => { const run = __t.mk("vault", {}, { tab: "history", toolName: "prime_factorization" }); return { state: { run, tool: __t.clone(findTool("prime_factorization")) }, html: panelHtml(run) }; } },
  { id: "panel/history-gone", build: () => { const run = __t.mk("vault", {}, { tab: "history", toolName: "nope" }); return { state: { run, tool: null }, html: panelHtml(run) }; } },
  // conversation (Task 10)
  { id: "convo/empty", build: () => { renderEmptyConvo(); return { state: {}, html: msgs.innerHTML }; } },
  { id: "convo/you", build: () => { msgs.innerHTML = ""; addYou('Encrypt "<b>x</b>" & more'); return { state: { text: 'Encrypt "<b>x</b>" & more' }, html: msgs.innerHTML }; } },
  { id: "convo/talos-thinking", build: () => { msgs.innerHTML = ""; const t = addTalos(); t.status("Planning"); return { state: { status: "Planning" }, html: msgs.innerHTML }; } },
  { id: "convo/seeded-fib", build: () => { const s = S.sessions.find((x) => x.id === "seed-fib"); return { state: { runs: s.runs.map(__t.clone) }, html: sessionHtml(s.runs) }; } },
  // dialogs (Task 10)
  { id: "dialog/approval-python", build: () => { approvalDialog("python_exec", "print(sum(range(1, 101)))"); const html = document.querySelector("#modal-root").innerHTML; S.dialog.close({ action: "cancel" }); return { state: { tool: "python_exec", code: "print(sum(range(1, 101)))" }, html }; } },
  { id: "dialog/approval-shell", build: () => { approvalDialog("shell_exec", "ls -la <dir>"); const html = document.querySelector("#modal-root").innerHTML; S.dialog.close({ action: "cancel" }); return { state: { tool: "shell_exec", code: "ls -la <dir>" }, html }; } },
  { id: "dialog/key", build: () => { keyDialog("get_current_temperature", "OPENWEATHERMAP_API_KEY", "OpenWeatherMap"); const html = document.querySelector("#modal-root").innerHTML; S.dialog.close({ action: "cancel" }); return { state: { toolName: "get_current_temperature", envVar: "OPENWEATHERMAP_API_KEY", service: "OpenWeatherMap" }, html }; } },
  { id: "dialog/reader-caesar", build: () => { readerDialog({ name: "caesar_cipher", src: "src-caesar" }); const html = document.querySelector("#modal-root").innerHTML; S.dialog.close({ action: "close" }); return { state: { name: "caesar_cipher", lines: getSource("src-caesar") }, html }; } },
  // vault (Task 11)
  { id: "vault/default", build: () => { S.selected = "caesar_cipher"; renderVault({ stagger: true }); return { state: { tools: __t.clone(S.vault), filter: "all", query: "", selected: null, stagger: true }, html: document.querySelector("#view-vault").innerHTML }; } },
  { id: "vault/fresh-selected", build: () => { S.vault.push({ name: "caesar_cipher", args: CAESAR.args, ret: CAESAR.ret, desc: CAESAR.desc, kw: CAESAR.kw, uses: 1, fails: 0, streak: 0, created: "2026-09-30T12:00", last: "2026-09-30T12:00", lastFail: "", lastFailAt: "", web: false, fresh: true, src: "src-caesar" }); S.selected = "caesar_cipher"; renderVault(); return { state: { tools: __t.clone(S.vault), filter: "all", query: "", selected: "caesar_cipher", stagger: false, source: getSource("src-caesar") }, html: document.querySelector("#view-vault").innerHTML }; } },
  { id: "vault/web", build: () => { S.filter = "web"; S.selected = "fetch_btc_price_usd"; renderVault({ stagger: true }); return { state: { tools: __t.clone(S.vault), filter: "web", query: "", selected: "fetch_btc_price_usd", stagger: true }, html: document.querySelector("#view-vault").innerHTML }; } },
  { id: "vault/failed-query", build: () => { S.filter = "failed"; S.query = "date"; S.selected = "normalize_date_strings"; renderVault(); return { state: { tools: __t.clone(S.vault), filter: "failed", query: "date", selected: "normalize_date_strings", stagger: false }, html: document.querySelector("#view-vault").innerHTML }; } },
  { id: "vault/empty", build: () => { S.query = "zzzz"; S.selected = null; renderVault(); return { state: { tools: __t.clone(S.vault), filter: "all", query: "zzzz", selected: null, stagger: false }, html: document.querySelector("#view-vault").innerHTML }; } },
  // sessions, settings (Task 12)
  { id: "sessions/boot", build: () => { renderSessions(); return { state: { sessions: S.sessions.map(__t.cloneSession), curId: S.cur.id }, html: document.querySelector("#sessions-in").innerHTML }; } },
  { id: "settings/default", build: () => { renderSettings(); return { state: { askExec: true, env: {} }, html: document.querySelector("#settings-in").innerHTML }; } },
  { id: "settings/off-key", build: () => { S.askExec = false; S.env.OPENWEATHERMAP_API_KEY = "k"; renderSettings(); return { state: { askExec: false, env: { OPENWEATHERMAP_API_KEY: "k" } }, html: document.querySelector("#settings-in").innerHTML }; } },
  // header (Task 7)
  { id: "header/default", build: () => ({ state: { busy: false, badge: false, popOpen: false, speed: 1, view: "workbench" }, html: document.querySelector("header.top").outerHTML }) },
  { id: "header/busy-badge-pop", build: () => { document.querySelector("#brand").classList.add("busy"); document.querySelector("#vault-badge").hidden = false; togglePop(true); document.querySelector('[data-speed="2"]').click(); location.hash = ""; showView("vault"); document.querySelector("#vault-badge").hidden = false; return { state: { busy: true, badge: true, popOpen: true, speed: 2, view: "vault" }, html: document.querySelector("header.top").outerHTML }; } },
  // seeds (Task 5)
  { id: "seeds/sessions", build: () => ({ state: {}, value: S.sessions.map(__t.cloneSession) }) },
];
