// Scripted flows over the real reference. Task 16 replays the same actions against the React app.
export const DEFAULT_REGIONS = ["header.top", "#msgs", "#live", "#bench", ".composer", "#modal-root"];

const SEND_READY = `document.querySelector("#send").textContent === "Send" && !document.querySelector("#brand").classList.contains("busy")`;
export const DONE = `(${SEND_READY}) && !document.querySelector("#modal-root .dialog")`;
export const DIALOG = `!!document.querySelector("#modal-root .dialog")`;

export const Q = {
  forge: 'Build a Caesar cipher tool that can both encrypt and decrypt. Encrypt "TALOS AGENT" with a shift of 7.',
  reuse: 'Decrypt this Caesar cipher message with shift 7: "AHSVZ HNLUA"',
  wordShift: 'Decrypt this Caesar cipher message with shift seven: "AHSVZ HNLUA"',
  python: "Run this Python code and give me the output: print(sum(range(1, 101)))",
  weather: "Use the OpenWeatherMap API to get the current temperature in Mumbai.",
  chat: "What can you do?",
  vaultlist: "How many tools are in your vault?",
  unknown: 'Summarise <b>this</b> PDF & "that" one',
};

const forge = [{ do: "click", sel: '[data-suggest="0"]' }, { do: "until", cond: DONE }];
const vaultRegions = ["#view-vault", "header.top"];

export const FLOWS = {
  boot: [{ do: "snap", name: "idle" }],
  "caesar-forge": [
    { do: "snapAt", name: "planning", cond: `!!document.querySelector('[data-node="planner"].active')` },
    { do: "snapAt", name: "forging", cond: `!!document.querySelector('.code-row[data-ln="30"]') && !!document.querySelector('[data-node="forger"].active')` },
    { do: "snapAt", name: "test-failed", cond: `!!document.querySelector(".tests li.failed")` },
    { do: "snapAt", name: "retry", cond: `!!document.querySelector('[data-node="forger"].active') && !!document.querySelector(".code-row.changed")` },
    { do: "snapAt", name: "smoke", cond: `!!document.querySelector(".smoke-body .caret")` },
    { do: "snapAt", name: "saved", cond: `!!document.querySelector(".banner:not(.removed)") && !document.querySelector('[data-node="executor"].active')` },
    { do: "snapAt", name: "args", cond: `document.querySelectorAll(".args dd").length === 2` },
    ...forge,
    { do: "snap", name: "end" },
    { do: "hash", value: "#vault" },
    { do: "snap", name: "vault", regions: vaultRegions },
    { do: "click", sel: '[data-read-src="caesar_cipher"]' },
    { do: "snap", name: "reader", regions: ["#modal-root"] },
    { do: "key", key: "Escape" },
    { do: "hash", value: "#sessions" },
    { do: "snap", name: "sessions", regions: ["#view-sessions"] },
    { do: "hash", value: "#settings" },
    { do: "snap", name: "settings", regions: ["#view-settings"] },
  ],
  "caesar-reuse": [
    ...forge,
    { do: "snapAt", name: "vault-step", cond: `!!document.querySelector('[data-node="vault"].done') && !document.querySelector('[data-node="executor"].active')` },
    { do: "submit", text: Q.reuse },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" },
    { do: "click", sel: '[data-tab="code"]' },
    { do: "snap", name: "code-tab" },
    { do: "click", sel: '[data-tab="history"]' },
    { do: "snap", name: "history-tab" },
    { do: "click", sel: '[data-tab="log"]' },
    { do: "snap", name: "log-tab" },
    { do: "click", sel: '.earlier button[data-run="6"]' },
    { do: "snap", name: "earlier-run" },
  ],
  "caesar-fail": [
    ...forge,
    { do: "submit", text: Q.wordShift },
    { do: "until", cond: DONE },
    { do: "snap", name: "fail-1" },
    { do: "submit", text: Q.wordShift },
    { do: "until", cond: DONE },
    { do: "snap", name: "fail-2" },
    { do: "hash", value: "#vault" },
    { do: "snap", name: "vault", regions: vaultRegions },
  ],
  "python-approve": [
    { do: "click", sel: '[data-suggest="2"]' },
    { do: "until", cond: DIALOG },
    { do: "snap", name: "dialog" },
    { do: "click", sel: '[data-d="yes"]' },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" },
  ],
  "python-decline": [
    { do: "click", sel: '[data-suggest="2"]' },
    { do: "until", cond: DIALOG },
    { do: "click", sel: '[data-d="no"]' },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" },
  ],
  "python-escape": [
    { do: "click", sel: '[data-suggest="2"]' },
    { do: "until", cond: DIALOG },
    { do: "key", key: "Escape" },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" },
  ],
  "python-no-ask": [
    { do: "hash", value: "#settings" },
    { do: "click", sel: "#ask-switch" },
    { do: "snap", name: "settings-off", regions: ["#view-settings"] },
    { do: "hash", value: "#workbench" },
    { do: "snap", name: "idle-off" },
    { do: "submit", text: Q.python },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" },
  ],
  "weather-save": [
    { do: "click", sel: '[data-suggest="3"]' },
    { do: "until", cond: DIALOG },
    { do: "snap", name: "dialog" },
    { do: "click", sel: '#modal-root button[type="submit"]' },
    { do: "snap", name: "dialog-error", regions: ["#modal-root"] },
    { do: "fill", sel: "#dlg-key", value: "owm-test-key" },
    { do: "click", sel: '#modal-root button[type="submit"]' },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" },
    { do: "hash", value: "#settings" },
    { do: "snap", name: "settings-key", regions: ["#view-settings"] },
    { do: "hash", value: "#workbench" },
    { do: "submit", text: Q.weather },
    { do: "until", cond: DONE },
    { do: "snap", name: "reuse-end" },
  ],
  "weather-skip": [
    { do: "click", sel: '[data-suggest="3"]' },
    { do: "until", cond: DIALOG },
    { do: "click", sel: '[data-d="skip"]' },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" },
    { do: "submit", text: Q.weather },
    { do: "until", cond: DONE },
    { do: "snap", name: "reuse-fail" },
  ],
  chat: [{ do: "submit", text: Q.chat }, { do: "until", cond: DONE }, { do: "snap", name: "end" }],
  vaultlist: [{ do: "submit", text: Q.vaultlist }, { do: "until", cond: DONE }, { do: "snap", name: "end" }],
  "unknown-html": [
    { do: "submit", text: Q.unknown },
    { do: "until", cond: DONE },
    { do: "snap", name: "end" }, // one-tab runs show the run log without a tab bar
    { do: "hash", value: "#sessions" },
    { do: "snap", name: "sessions", regions: ["#view-sessions"] },
  ],
  "stop-during-tests": [
    { do: "at", cond: `!!document.querySelector(".tests li.running")`, click: ['[data-action="stop"]'] },
    ...forge,
    { do: "snap", name: "end" },
  ],
  "reset-mid-run": [
    { do: "at", cond: `!!document.querySelector('.code-row[data-ln="10"]')`, click: ["#demo-toggle", "#demo-reset"] },
    { do: "click", sel: '[data-suggest="0"]' },
    { do: "until", cond: `(${SEND_READY}) && !!document.querySelector("#bench .idle")` },
    { do: "snap", name: "end" },
    { do: "hash", value: "#sessions" },
    { do: "snap", name: "sessions", regions: ["#view-sessions"] },
  ],
  sessions: [
    ...forge,
    { do: "click", sel: "#new-session" },
    { do: "snap", name: "new-session" },
    { do: "hash", value: "#sessions" },
    { do: "snap", name: "list", regions: ["#view-sessions"] },
    { do: "click", sel: '[data-open-session="seed-fib"]' },
    { do: "until", cond: `!!document.querySelector(".viewing-note")` },
    { do: "snap", name: "old-session" },
    { do: "click", sel: '.run-link[data-run="1"]' },
    { do: "snap", name: "old-run" },
    { do: "click", sel: "#back-session" },
    { do: "snap", name: "back-to-now" },
  ],
  "vault-browse": [
    { do: "hash", value: "#vault" },
    { do: "snap", name: "default", regions: vaultRegions },
    { do: "fill", sel: "#v-search", value: "hex" },
    { do: "snap", name: "search", regions: vaultRegions },
    { do: "fill", sel: "#v-search", value: "zzzz" },
    { do: "snap", name: "empty", regions: vaultRegions },
    { do: "fill", sel: "#v-search", value: "" },
    { do: "click", sel: '[data-filter="web"]' },
    { do: "snap", name: "web", regions: vaultRegions },
    { do: "click", sel: '[data-filter="failed"]' },
    { do: "snap", name: "failed", regions: vaultRegions },
    { do: "click", sel: '[data-tool="flatten_json"]' },
    { do: "snap", name: "detail", regions: vaultRegions },
    { do: "click", sel: '[data-remove-tool="flatten_json"]' },
    { do: "snap", name: "confirm", regions: vaultRegions },
    { do: "click", sel: '[data-remove-tool="flatten_json"]' },
    { do: "snap", name: "removed", regions: vaultRegions },
  ],
  "demo-controls": [
    { do: "click", sel: "#demo-toggle" },
    { do: "snap", name: "open", regions: ["header.top"] },
    { do: "click", sel: '[data-speed="2"]' },
    { do: "snap", name: "fast", regions: ["header.top"] },
    { do: "key", key: "Escape" },
    { do: "snap", name: "closed", regions: ["header.top"] },
  ],
};
