import { PRUNE_AT } from "./routing";

/** Every user-facing string the frontend owns, verbatim from the reference. `{name}` marks a value. */
export const COPY = {
  brand: { aria: "Talos, open the workbench", word: "TALOS" },
  nav: { aria: "Main", workbench: "Workbench", vault: "Vault", sessions: "Sessions", settings: "Settings" },
  demo: {
    toggle: "Demo controls",
    blurb: "Scripted runs over the real Talos vault. Nothing calls a model or leaves your browser.",
    speed: "Run speed",
    slow: "Slow",
    normal: "Normal",
    fast: "Fast",
    reset: "Reset the demo",
  },
  github: { label: "GitHub", href: "https://github.com/Yathharth54/Talos-AI" },
  convo: {
    aria: "Conversation",
    sessionName: "Session {n}",
    newSession: "New session",
    backToNow: "Back to now",
    askLabel: "Ask Talos",
    placeholder: "Ask for something it can't do yet",
    hintIdle: "Enter to send, Shift+Enter for a new line",
    hintBusy: "Stop the run to ask something else",
    hintPast: "Viewing an old session. Go back to {name} to ask something.",
    send: "Send",
    working: "Working",
    you: "You",
    talos: "Talos",
    thinking: "Working on it",
    viewRun: "View this run",
    empty: "Messages from this session show up here. Talos keeps the conversation until you close it; the vault stays on disk.",
    readOnly: "{name}, {time}. Read only.",
    livePrefix: "Talos: ",
    stopped: "Stopped. Ask again whenever you're ready.",
  },
  idle: {
    heading: "Ask for something it can't do yet",
    lede: " tools are already in the vault. Anything missing, Talos writes, tests, and keeps, so the next similar request skips straight to the answer.",
    tryHeading: "Try one of these",
    setup: "{keys} keys set in .env. Ask before running code is {state}. ",
    keysWithWeather: "3 of 5",
    keysWithout: "2 of 4",
    keysOfTotal: "{set} of {total}",
    on: "on",
    off: "off",
    settings: "Settings",
  },
  bench: {
    aria: "Bench",
    stop: "Stop run",
    graph: "Graph progress",
    reading: "Reading your request",
    planning: "Planning",
    noTools: "No tools needed",
    details: "Details",
    tabs: { code: "Code", tests: "Tests", attempts: "Attempts", call: "Call", history: "History", log: "Run log" },
  },
  banner: {
    savedAria: "Saved to the vault",
    saved: " is in the vault",
    openInVault: "Open in vault",
    removedAria: "Removed from the vault",
    removed: " was removed from the vault",
  },
  code: { aria: "Source code", cap: "{n} lines, attempt {a}", lines: "{n} lines" },
  tests: {
    none: "Tests appear here once the Forger has written them.",
    passedOf: "{p} of {k} passed",
    running: "Attempt {n}, running",
    unit: "Unit tests",
    smoke: "Smoke test",
    smokeCap: "Real input, run once",
    smokeRunning: "running",
    passed: "passed",
    failed: "failed",
    prevFailed: "Attempt {n} failed one test",
    note: "Tests run in a fresh subprocess inside a temporary folder, with a {s}-second limit. They can't touch the network or your files.",
  },
  attempts: {
    none: "No attempts yet.",
    n: "Attempt {n}",
    underTest: "Under test",
    passed: "Passed every test",
    failed: "Failed",
    note: "The Forger gets up to 3 attempts. Each failure goes back to it with the failing test and its traceback.",
  },
  call: {
    none: "None",
    args: "Arguments",
    argsCap: "Filled in by the Executor",
    resolving: "resolving",
    errorCap: "The tool raised an error",
    declinedWhen: "You chose Don't run",
    result: "Result",
    waiting: "Waiting for the Executor",
    output: "Output",
    awaitingApproval: "Waiting for your approval",
    running: "running",
    record: "Tool record",
    forged: "Forged",
    uses: "Uses",
    failures: "Failures",
    recordUses: "{n}, including this one",
    recordFails: "{n} in total",
    recordNone: "None yet",
    health: "What this means for the vault",
    meter: "{s} of {p} failures in a row",
    streakOne: "{s} failure in a row",
    streakMany: "{s} failures in a row",
    openInVault: "Open in vault",
    retry: "Ask again with {arg} {digit}",
  },
  health: {
    caesar_cipher: {
      pruned: 'That was {p} failures with no success in between, so Talos took <span class="mono">caesar_cipher</span> out of the vault.',
      streak:
        'If <span class="mono">caesar_cipher</span> fails again before it next succeeds, Talos takes it out of the vault and forges a fresh one next time. One success resets the count. The .py file stays on disk either way.',
    },
    get_current_temperature: {
      pruned: "Removed after two failures in a row.",
      streak: "Set the key and ask again. One success resets the count.",
    },
    generic: {
      pruned: 'That was {p} failures with no success in between, so Talos took <span class="mono">{tool}</span> out of the vault.',
      streak:
        'If <span class="mono">{tool}</span> fails again before it next succeeds, Talos takes it out of the vault and forges a fresh one next time. One success resets the count. The .py file stays on disk either way.',
    },
  },
  removedSub: {
    caesar_cipher: "It failed {p} times in a row, so the next Caesar request will forge a fresh one. The .py file stays on disk.",
    get_current_temperature: "It failed {p} times in a row. The next weather request forges a fresh one.",
    generic: "It failed {p} times in a row, so the next {tool} request will forge a fresh one. The .py file stays on disk.",
  },
  history: {
    gone: "This tool is no longer in the vault.",
    forged: "Forged",
    lastUsed: "Last used",
    uses: "Uses",
    failures: "Failures",
    failuresValue: "{f} in total, {s} in a row",
    lastFailure: "Last failure",
  },
  log: {
    thisRun: "This run",
    runN: "Run {n}",
    note: "Each line is a node in the graph. With LangSmith set up, the whole run is traced there too.",
    inSession: "In this session",
    earlier: "Earlier in this session",
    prompt: "talos › ",
  },
  approval: {
    eyebrow: "{tool} needs your approval",
    titleCode: "Run this code on your machine?",
    titleShell: "Run this command on your machine?",
    body: "Talos wrote it to answer your question. It runs as you, with your file access, and stops after 10 seconds.",
    no: "Don't run",
    yesCode: "Run code",
    yesShell: "Run command",
    footA: "To stop asking, turn off ",
    footLink: "Ask before running code",
    footB: " in Settings, or set ",
    footVar: "TALOS_AUTO_APPROVE_EXEC=true",
    footC: " in .env.",
  },
  key: {
    eyebrow: "Human check",
    title: "This tool needs an {service} key",
    body: " reads its key from an environment variable. Talos saves what you paste to .env, so it only asks once.",
    placeholder: "Paste the key",
    skip: "Skip",
    save: "Save key",
    foot: "If you skip, the tool is still saved to the vault, but it fails when it runs until the key is set.",
    footDemo: " This demo keeps the key in memory only.",
    error: "Paste the key first, or choose Skip.",
  },
  reader: {
    title: "talos/vault/tools/{name}.py",
    sub: "{n} lines. Forged, tested and saved by Talos.",
    copy: "Copy",
    close: "Close",
    copied: "Copied",
    selected: "Selected, press Ctrl+C",
    aria: "Full source",
  },
  vault: {
    title: "Vault",
    lede: "{n} tools, every one written and tested by Talos. Stored as .py files and a manifest.json.",
    searchLabel: "Search the vault",
    searchPlaceholder: "Search by name or keyword",
    filterAria: "Filter",
    all: "All",
    web: "Uses the web",
    failed: "Has failed",
    colTool: "Tool",
    colUses: "Uses",
    colFailures: "Failures",
    colLast: "Last used",
    legend: "Gold names reach the web through a free API Talos found itself",
    showing: "Showing {r} of {n}",
    newTag: "New this session",
    notYet: "Not yet",
    empty: "No tools match. Try another word, or clear the filter.",
    detailAria: "Tool details",
    pick: "Pick a tool to see its record.",
    keywords: "Keywords",
    forged: "Forged",
    lastUsed: "Last used",
    uses: "Uses",
    failures: "Failures",
    none: "None",
    failuresValue: "{f} in total, {s} in a row",
    lastFailure: "Last failure",
    file: "File",
    filePath: "talos/vault/tools/{name}.py",
    reachesWeb: "Reaches the web",
    webYes: "Yes, through a free API it found itself",
    webNo: "No",
    healthAria: "Vault health",
    healthOne: "One more failure in a row removes it",
    healthOk: "Healthy. No failures in a row",
    healthNote: "A success resets the count. Removing a tool only drops it from manifest.json; the .py file stays for you to read.",
    previewName: "{name}.py",
    previewSub: "{n} lines, written by the Forger",
    read: "Read full file",
    previewAria: "Source code preview",
    noSource: "Source lives at talos/vault/tools/{name}.py. This demo only bundles the source of tools it forges.",
    use: "Use in a question",
    remove: "Remove from vault",
    confirm: "Remove {name}?",
    usePrefill: "Use {name} on ",
  },
  sessions: {
    title: "Sessions",
    lede: "Every conversation, and what it forged or reused. Sessions end; the vault they build is shared by all of them.",
    today: "Today",
    run: "run",
    runs: "runs",
    forgedCount: ", {n} forged",
    now: "Now",
    empty: "Nothing asked yet.",
    more: "and {n} more",
    cont: "Continue",
    open: "Open",
  },
  settings: {
    title: "Settings",
    safety: "Safety",
    ask: "Ask before running code",
    askA: "Talos shows you every ",
    askPython: "python_exec",
    askB: " and ",
    askShell: "shell_exec",
    askC: " call and waits for you. Turning this off is the same as ",
    askVar: "TALOS_AUTO_APPROVE_EXEC=true",
    keys: "Keys",
    set: "Set",
    notSet: "Not set",
    forging: "Forging",
    model: "Model",
    retries: "Forge retries",
    testLimit: "Test time limit",
    testLimitValue: "10 seconds",
    modelLimit: "Model call time limit",
    modelLimitValue: "120 seconds",
    secondsValue: "{n} seconds",
    pruneAfter: "Removed from the vault after",
    pruneValue: "{n} failures in a row",
    note: "These come from .env. Change them there and restart Talos.",
    keyDesc: {
      OPENROUTER_API_KEY: "Required. Every model call goes through OpenRouter.",
      TAVILY_API_KEY: "Needed for web search.",
      JINA_API_KEY: "Optional. Raises web-reading limits.",
      LANGSMITH_API_KEY: "Optional. Traces every node in LangSmith.",
      savedByHuman: "Saved by Human check this session.",
      askedWhenNeeded: "Asked for when a tool needs it.",
    },
  },
} as const;

export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
}

type Keyed = { pruned: string; streak: string };
const keyed = (table: Record<string, Keyed>, tool: string): Keyed => table[tool] ?? (table.generic as Keyed);

/** The health panel's paragraph after a vault/forged tool failed (lines 1728–1730, 1884). Ruling 9. */
export function healthText(tool: string, pruned: boolean): string {
  const t = keyed(COPY.health as unknown as Record<string, Keyed>, tool);
  return fill(pruned ? t.pruned : t.streak, { p: PRUNE_AT, tool });
}
/** The removed banner's second line (lines 1722, 1883). */
export function removedSub(tool: string): string {
  const table = COPY.removedSub as unknown as Record<string, string>;
  return fill(table[tool] ?? COPY.removedSub.generic, { p: PRUNE_AT, tool });
}
export const retryLabel = (arg: string, digit: number): string => fill(COPY.call.retry, { arg, digit });
